=== NikoHOME/hih/recipe.dtd
<?xml version="1.0" encoding="UTF-8"?>
    <!ENTITY % basicData "CDATA #REQUIRED">
    <!ELEMENT recipeList (recipeSection*)>
    <!ELEMENT recipeSection (recipe*)>
    <!ATTLIST recipeSection type %basicData;> 
    <!ELEMENT recipe (name,description,(links|(images,links)),ingredients,steps,nutrition?)>
    <!ATTLIST recipe difficulty %basicData;>
    <!ATTLIST recipe time %basicData;>
    <!ATTLIST recipe isVegan (true|false) "false">
    <!ATTLIST recipe isVege (true|false) "false">
    <!ATTLIST recipe sizemin %basicData;>
    <!ATTLIST recipe sizemax %basicData;>

    <!ELEMENT name (#PCDATA)>
    <!ELEMENT description (#PCDATA)>

    <!ENTITY % list "entry*">

    <!ELEMENT images (image*)>
    <!ELEMENT links (link*)>
    <!ELEMENT ingredients (%list;)>
    <!ELEMENT steps (%list;)>

    <!ELEMENT image (#PCDATA)>
    <!ATTLIST image file %basicData;>
    <!ELEMENT link (#PCDATA)>
    <!ATTLIST link url %basicData;>
    <!ELEMENT entry (#PCDATA)>
    <!ATTLIST entry n %basicData;>

    <!ELEMENT nutrition (calories,carbs,fat,protein,extra?)>
    <!ELEMENT calories (#PCDATA)>
    <!ELEMENT carbs (#PCDATA)>
    <!ELEMENT fat (#PCDATA)>
    <!ELEMENT protein (#PCDATA)>
    <!ELEMENT extra (#PCDATA)>

=== NikoHOME/hih/recipes.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE recipeList SYSTEM "recipe.dtd">
<recipeList>

    <recipeSection type="breakfast">
        <recipe difficulty="medium" time="15" isVegan="false" isVege="true" sizemin="1" sizemax="2">
            <name>Japoński zawijany omlet</name>
            <description>
                Oryginalny japonski omlet zawijany jest smazony na podluznej, prostokatnej patelni i posiada w swoim skladzie m.in. sos sojowy i mirin - japonskie wino ryzowe, które jest popularna przyprawa do gotowania.  Omlety te czesto nie posiadaja zadnych dodatków, choc istnieja jednak omlety z cebula, marchewka, dymka lub wodorostami. Mój omlet posiada skladniki, które zawsze mamy w  domu, a oprócz typowo japonskiego sposobu na  smazenie zastosowalam arkusz nori, ale i bez niego przepis jest równie smaczny. Co do innych warzyw fantazja nie zna granic, wiec praktycznie mozemy  za kazdym razem wyczarowac inne, bardzo szybkie  danie.
            </description>
            <images> 
                <image file="omlet.jpg">
                    Omlet
                </image>
            </images>
            <links>
                <link url="https://smaker.pl/przepisy-dania-glowne/przepis-japonski-zawijany-omlet,173106,konhambos.html">
                    Smaker Omlet
                </link>
            </links>
            <ingredients>
                <entry n="1">
                    5 jajek
                </entry>
                <entry n="2">
                    2 łyżki mleka
                </entry>
                <entry n="3">
                    2 dymki lub szalotki
                </entry>
                <entry n="4">
                    1 marchewka
                </entry>
                <entry n="5">
                    1 arkusz nori (wodorostów) opcjonalnie
                </entry>
                <entry n="6">
                    olej
                </entry>
                <entry n="7">
                    sól, pieprz
                </entry>
            </ingredients>
            <steps>
                <entry n="1">
                    Pokroic marchewke w bardzo drobna kostke a dymke na drobne pierscienie.
                </entry>
                <entry n="2">
                    Wymieszac jajka z mlekiem i przyprawami i przecedzic przez sitko. Jednolita mase jajeczna wymieszac z marchewka i dymka.
                </entry>
                <entry n="3">
                    Umiescic okolo 1/3 masy na nagrzanej i natluszczonej, ale niezbyt goracej patelni i ulozyc na niej arkusz wodorostów.
                </entry>
                <entry n="4">
                    Gdy masa sie zetnie, delikatnie ja zrolowac, przesunac do konca patelni i wlac nastepna czesc masy na zwolnione miejsce uwazajac, aby masa znalazla sie równiez pod zwinietym jajkiem.
                </entry>
                <entry n="5">
                    Gdy nowa warstwa sie zetnie, ponownie ja zrolowac a na wolne miejsce wlac nastepna czesc masy i powtarzac wszystko do momentu, az masa jajeczna zostanie zuzyta.
                </entry>
                <entry n="6">
                    Gdy omlet jest gotowy, wyjac go z patelni, chwile ostudzic i przeciac na waskie kawalki.
                </entry>
            </steps>

        </recipe>

    <recipe difficulty="easy" time="25" isVegan="false" isVege="true" sizemin="1" sizemax="2">
            <name>Pannkakor, szwedzkie naleśniki</name>
            <description>
                „Pannkaka” w języku szwedzkim oznacza naleśnika. W Szwecji naleśniki smaży się na patelni lub piecze w piekarniku (pieczone naleśniki są popularne także w innych krajach skandynawskich). Naleśniki mogą być podawane ze słodkimi lub wytrawnymi dodatkami
            </description>
            <images>
                <image file="pancake.jpg">
                    Naleśnik
                </image>
            </images>
            <links>
                <link url="https://filozofiasmaku.pl/2014/05/15/pannkakor-szwedzkie-nalesniki/">
                    Filozofia Smaku pannakator
                </link>
            </links>
            <ingredients>
                <entry n="1">
                    1 szklanka mąki
                </entry>
                <entry n="2">
                    szczypta soli
                </entry>
                <entry n="3">
                    2 szklanki mleka
                </entry>
                <entry n="4">
                    3 jajka
                </entry>
                <entry n="5">
                    2 łyżki stopionego masła
                </entry>
            </ingredients>
            <steps>
                <entry n="1">
                    Mąkę przesiewamy do miski, dodajemy szczyptę soli, mleko, jajka i ostudzone stopione masło.
                </entry>
                <entry n="2">
                    Całość mieszamy przy pomocy miksera lub ręcznej trzepaczki (do połączenia składników).
                </entry>
                <entry n="3">
                    Odstawiamy na 15-30 minut.
                </entry>
                <entry n="4">
                    Na patelni do naleśników topimy niewielką ilość masła (lub używamy oleju), przy pomocy chochelki wylewamy porcje ciasta, rozprowadzamy po dnie patelni. Smażymy z obu stron, aż ładnie się zrumienią.
                </entry>
                <entry n="5">
                    Należy uważać przy odwracaniu naleśników na drugą stronę, ciasto będzie cienkie i delikatne.
                </entry>
                <entry n="6">
                    Pannkakor podajemy z bitą śmietaną, dżemem (u mnie dżem malinowy) i owocami. 
                </entry>
            </steps>
            <nutrition>
                <calories>66</calories>
                <carbs>8g</carbs>
                <fat>3g</fat>
                <protein>3g</protein>
            </nutrition>
        </recipe>
    </recipeSection>
    <recipeSection type="dinner">
        <recipe difficulty="medium" time="180" isVegan="false" isVege="false" sizemin="6" sizemax="8">
            <name>Bolognese Tagliatelle</name>
            <description>
                Tagliatelle alla bolognese (tagliatelle z sosem bolognese) są pierwszym daniem kuchni włoskiej a właściwie kuchni regionu Emilia-Romagna, ze starożytnymi i arystokratycznymi korzeniami. Często są mylnie nazywane spaghetti alla bolognese.
            </description>
            <images>            
                <image file="bologne.jpg">
                    Sos boloński
                </image>
            </images>
            <links>
                <link url="https://www.allrecipes.com/recipe/280810/bolognese-tagliatelle/">
                    Allrecipes boloński tagiatelle
                </link>
            </links>
            <ingredients>
                <entry n="1">
                    500 g Makaronu Tagliatelle
                </entry>
                <entry n="2">
                    500 g Mielonej wołowiny
                </entry>
                <entry n="3">
                    250 g Mielonej wieprzowiny
                </entry>
                <entry n="4">
                    250 g Przeciera pomidorowego (passata)
                </entry>
                <entry n="5">
                    50 g Selera
                </entry>
                <entry n="6">
                    50 g Cebuli
                </entry>
                <entry n="7">
                    50 g Marchewki
                </entry>
                <entry n="8">
                    0,25L Białego wina
                </entry>
                <entry n="9">
                    Oliwa z oliwek extravirgin
                </entry>
                <entry n="10">
                    3L Wody
                </entry>
                <entry n="11">
                    0,25L Mleka
                </entry>
                <entry n="12">
                    Sól Pierz
                </entry>
            </ingredients>
            <steps>
                <entry n="1">
                    Aby przygotować sos bolognese, obierz marchewkę i cebulę i odetnij końce z łodyg selera. Pokrój warzywa w drobną kostkę.
                </entry>
                <entry n="2">
                    Wlej łyżkę oleju do rondla i dodaj warzywa, podsmaż na małym ogniu przez około 10 minut, mieszając od czasu do czasu aż dno patelni będzie suche.
                </entry>
                <entry n="3">
                    Dodaj mieloną wołowinę i wieprzowinę od czasu do czasu mieszając. Nawet te będą musiały powoli przyrumienić przez około 10 minut.
                </entry>
                <entry n="4">
                    Polej białym winem i pozwól mu wyparować na dużym ogniu.
                </entry>
                <entry n="5">
                    Jak tylko alkohol wyparuje i jeszcze raz dno się wysuszy, zmniejsz ogień i dodaj przecier pomidorowy.
                </entry>
                <entry n="6">
                    Następnie wlej tylko 1 z 3 litrów wody, dodaj szczyptę soli, wymieszaj i gotuj na średnim ogniu przez godzinę.
                </entry>
                <entry n="7">
                    Dodaj kolejny litr wody, wymieszaj i gotuj przez kolejną godzinę.
                </entry>
                <entry n="8">
                    Pod koniec drugiej godziny gotowania dolej ostatni litr wody i kontynuuj gotowanie na małym ogniu przez kolejną godzinę.
                </entry>
                <entry n="9">
                    W ten sposób sos będzie gotował się przez co najmniej 3 godziny.
                </entry>
                <entry n="10">
                    Dopraw solą i pieprzem, wyłącz ogień, dodaj mleko i wymieszaj.
                </entry>
                <entry n="11">
